name: flutter_boost
description: A next-generation Flutter-Native hybrid solution. FlutterBoost is a Flutter plugin which enables hybrid integration of Flutter for your existing native apps with minimum efforts.
version: 1.12.13+1
author: Alibaba Xianyu
homepage: https://github.com/alibaba/flutter_boost

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: 4.1.1

flutter:
  plugin:
    androidPackage: com.idlefish.flutterboost
    pluginClass: FlutterBoostPlugin
